// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Address = import("./address").Address;
export type Link = import("./link").Link;
export type LinkList = import("./link-list").LinkList;
