// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Youtube = {
  /**
   * Url
   */
  url: string;

  /**
   * Width
   */
  width?: string;

  /**
   * Autoplay
   */
  autoplay: string;

  /**
   * Size
   */
  size?: "small" | "large";
};
