// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type TwoColumns = import("./two-columns").TwoColumns;

export type LayoutMap = {
  "no.item.example:two-columns": TwoColumns;
};

declare global {
  interface XpLayoutMap {
    "no.item.example:two-columns": TwoColumns;
  }
}
