// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type ArticleView = import("./article-view").ArticleView;

export type PartMap = {
  "no.item.example:article-view": ArticleView;
};

declare global {
  interface XpPartMap {
    "no.item.example:article-view": ArticleView;
  }
}
