// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type MenuItem = import("./menu-item").MenuItem;
export type Seo = import("./seo").Seo;

declare global {
  interface XpXData {
    "no-item-example"?: {
      "menu-item"?: MenuItem;
      seo?: Seo;
    };
  }
}
