// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Default = import("./default").Default;

export type PageMap = {
  "no.item.example:default": Default;
};

declare global {
  interface XpPageMap {
    "no.item.example:default": Default;
  }
}
