package no.item.xp.codegen

import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.plugins.JavaPlugin
import org.gradle.api.tasks.SourceSetContainer
import java.io.File

const val DEFAULT_PREPEND_TEXT =
  "// WARNING: This file was automatically generated by \"no.item.xp.codegen\". You may lose your changes if you edit it."

abstract class CodegenPlugin : Plugin<Project> {
  override fun apply(project: Project) {
    project.plugins.withType(JavaPlugin::class.java) {
      val sourceSets = project.extensions.getByType(SourceSetContainer::class.java)
      val projectDirectory = project.layout.projectDirectory
      val outputDirectory = projectDirectory.dir(".xp-codegen")

      project.tasks.register("generateTypeScript", GenerateTypeScriptTask::class.java) { task ->
        task.group = "xp"
        task.description = "Generates TypeScript types based on the YAML descriptors of the application"
        task.resourceDirectories.from(sourceSets.named("main").map { it.resources.sourceDirectories })
        task.includedJars.from(project.configurations.matching { it.name == "include" && it.isCanBeResolved })
        task.editorConfigFiles.from(
          project.provider { findEditorConfigFileCandidates(projectDirectory.asFile).filter { it.isFile } },
        )
        task.singleQuote.convention(false)
        task.prependText.convention(DEFAULT_PREPEND_TEXT)
        task.declareGlobals.convention(false)
        task.appName.convention(project.providers.gradleProperty("appName"))
        task.outputDirectory.convention(outputDirectory)
      }
    }
  }
}

/**
 * Returns the ".editorconfig" files that can affect the generated files
 */
private fun findEditorConfigFileCandidates(projectDirectory: File): List<File> =
  listOf(File(projectDirectory, ".xp-codegen/.editorconfig")) +
    generateSequence(projectDirectory.absoluteFile) { it.parentFile }.map { File(it, ".editorconfig") }
