// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type JarXData = import("./jar-x-data").JarXData;

declare global {
  interface XpXData {
    "no-item-example"?: {
      "jar-x-data"?: JarXData;
    };
  }
}
