// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type TwoColumns = {
  /**
   * Column ratio
   */
  columnRatio: "50-50" | "30-70";
};
