// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Address = {
  /**
   * Street
   */
  street?: string;

  /**
   * Postal code
   */
  postalCode?: string;

  /**
   * Url
   */
  url: string;

  /**
   * Open in new tab
   */
  openInNewTab: boolean;
};
