// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type JarMixin = import("./jar-mixin").JarMixin;

export type MixinMap = {
  "no-item-example"?: {
    "jar-mixin"?: JarMixin;
  };
};
