package no.item.xp.plugin.snapshots

import org.gradle.testkit.runner.GradleRunner
import org.junit.jupiter.api.Assertions.assertAll
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.function.Executable
import org.junit.jupiter.api.io.TempDir
import java.io.File
import java.util.jar.JarEntry
import java.util.jar.JarOutputStream
import kotlin.test.assertContains
import kotlin.test.assertEquals

private val SNAPSHOTS_DIR = File(System.getProperty("snapshotsDir") ?: "src/test/snapshots")
private val UPDATE_SNAPSHOTS = System.getProperty("updateSnapshots") == "true"

// Paths (relative to the project) of the files generated by the plugin
private val GENERATED_PATHS = listOf(".xp-codegen", "src/main/resources/i18n/phrases.tmp.properties")

private val BUILD_SCRIPT =
  """
  plugins {
    id "java"
    id "no.item.xp.codegen"
  }

  configurations {
    include
  }

  dependencies {
    include fileTree(dir: "libs", include: "*.jar")
  }

  """.trimIndent() + "\n"

/**
 * Runs the plugin on the project in "src/test/snapshots/<input>/input", and compares every generated file with the
 * files in "src/test/snapshots/<name>/expected". If "src/test/snapshots/<input>/jar" exists, it is added to the
 * project as a jar in the "include" configuration.
 *
 * These tests only depend on the files that the plugin generates, so they should keep passing through a rewrite of
 * the plugin. Run "./gradlew test -PupdateSnapshots=true" to replace the expected files with the current output.
 */
class GenerateCodeSnapshotTest {
  @TempDir
  lateinit var projectDir: File

  @Test
  fun `generate types for all kinds of descriptors`() {
    assertSnapshot("basic")
  }

  @Test
  fun `generate global maps with app name`() {
    assertSnapshot("app-name", input = "basic", arguments = listOf("-PappName=no.item.example"))
  }

  @Test
  fun `use single quotes and custom prepend text`() {
    assertSnapshot(
      "options",
      buildScript =
        """
        generateTypeScript {
          singleQuote = true
          prependText = "/* eslint-disable */"
        }
        """.trimIndent(),
    )
  }

  @Test
  fun `generate types for descriptors in included jars`() {
    assertSnapshot("include-jar", arguments = listOf("-PappName=no.item.example"))
  }

  @Test
  fun `fail if the same field name is used twice in the same object`() {
    val result = createRunner("duplicate-field-name").buildAndFail()

    assertContains(result.output, "Duplicate field name \"intro\" in \"site/content-types/article/article.xml\"")
  }

  @Test
  fun `fail if mixins have cyclic dependencies`() {
    val result = createRunner("cyclic-mixins").buildAndFail()

    assertContains(result.output, "Mixins has cyclic dependencies and cannot be resolved")
  }

  private fun assertSnapshot(
    name: String,
    input: String = name,
    arguments: List<String> = emptyList(),
    buildScript: String = "",
  ) {
    val result = createRunner(input, arguments, buildScript).build()
    val actual = readFiles(projectDir, GENERATED_PATHS)
    val expectedDir = File(SNAPSHOTS_DIR, "$name/expected")

    if (UPDATE_SNAPSHOTS) {
      expectedDir.deleteRecursively()
      actual.forEach { (path, content) ->
        File(expectedDir, path).apply { parentFile.mkdirs() }.writeText(content)
      }
      return
    }

    val expected = readFiles(expectedDir, listOf(""))

    assertEquals(
      expected.keys.sorted().joinToString("\n"),
      actual.keys.sorted().joinToString("\n"),
      "The generated files are not the same as in $expectedDir\n\n${result.output}",
    )

    assertAll(
      expected.map { (path, content) ->
        Executable { assertEquals(content, actual[path], "The content of $path is not the same") }
      },
    )
  }

  private fun createRunner(
    input: String,
    arguments: List<String> = emptyList(),
    buildScript: String = "",
  ): GradleRunner {
    File(SNAPSHOTS_DIR, "$input/input").copyRecursively(projectDir)
    File(SNAPSHOTS_DIR, "$input/jar")
      .takeIf { it.isDirectory }
      ?.let { createJar(it, File(projectDir, "libs/included.jar")) }
    File(projectDir, "settings.gradle").writeText("rootProject.name = \"snapshot\"\n")
    File(projectDir, "build.gradle").writeText(BUILD_SCRIPT + buildScript)

    return GradleRunner
      .create()
      .withProjectDir(projectDir)
      .withPluginClasspath()
      .withArguments(listOf("generateTypeScript", "generateI18nPhrases") + arguments)
  }
}

private fun readFiles(
  rootDir: File,
  paths: List<String>,
): Map<String, String> =
  paths
    .flatMap { File(rootDir, it).walkTopDown().filter { file -> file.isFile }.toList() }
    .associate { it.relativeTo(rootDir).invariantSeparatorsPath to readNormalized(it) }

private fun readNormalized(file: File): String {
  val content = file.readText().replace("\r\n", "\n")

  // Properties.store() writes the current date as a comment
  return if (file.extension == "properties") {
    content.lines().filterNot { it.startsWith("#") }.joinToString("\n")
  } else {
    content
  }
}

private fun createJar(
  sourceDir: File,
  jarFile: File,
) {
  jarFile.parentFile.mkdirs()

  JarOutputStream(jarFile.outputStream()).use { jar ->
    sourceDir
      .walkTopDown()
      .filter { it.isFile }
      .sortedBy { it.invariantSeparatorsPath }
      .forEach { file ->
        jar.putNextEntry(JarEntry(file.relativeTo(sourceDir).invariantSeparatorsPath))
        file.inputStream().use { it.copyTo(jar) }
        jar.closeEntry()
      }
  }
}
