// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type AllInputs = {
  /**
   * Text line
   */
  textLine?: string;

  /**
   * Required text line
   */
  requiredTextLine: string;

  /**
   * Text lines
   */
  textLines?: Array<string> | string;

  /**
   * Required text lines
   */
  requiredTextLines: Array<string> | string;

  /**
   * Text line with regexp
   */
  textLineWithRegexp?: string;

  /**
   * Text line with max length
   */
  textLineWithMaxLength?: string;

  /**
   * Text area
   */
  textArea?: string;

  /**
   * Html area
   */
  htmlArea?: string;

  /**
   * Long
   */
  long?: number;

  /**
   * Long with min and max
   */
  longWithMinAndMax?: number;

  /**
   * Doubles
   */
  doubles: Array<number> | number;

  /**
   * Date
   */
  date?: string;

  /**
   * Time
   */
  time?: string;

  /**
   * Date time
   */
  dateTime?: string;

  /**
   * Check box
   */
  checkBox: boolean;

  /**
   * Combo box
   */
  comboBox?: Array<"one" | "two"> | "one" | "two";

  /**
   * Radio button
   */
  radioButton: "yes" | "no";

  /**
   * Content selector
   */
  contentSelector?: Array<string> | string;

  /**
   * Image selector
   */
  imageSelector?: string;

  /**
   * Media selector
   */
  mediaSelector?: string;

  /**
   * Attachment uploader
   */
  attachmentUploader?: string;

  /**
   * Custom selector
   */
  customSelector?: string;

  /**
   * Tag
   */
  tag?: Array<string> | string;

  /**
   * Geo point
   */
  geoPoint?: string;

  /**
   * Content type filter
   */
  contentTypeFilter?: string;

  /**
   * Unknown type
   */
  unknownType?: unknown;

  /**
   * Hyphenated field
   */
  "my-hyphenated-field"?: string;


  withoutLabel?: string;

  /**
   * First line
   * Second line
   */
  multiLineLabel?: string;
};
