// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type SiteConfig = XP.SiteConfig;

declare global {
  namespace XP {
    interface SiteConfig {
      /**
       * Google Analytics id
       */
      googleAnalyticsId?: string;

      /**
       * Footer link
       */
      footerLink?:
        | {
            /**
             * Selected
             */
            _selected: "link";

            /**
             * Link
             */
            link: import("./form-fragments/link").Link;
          };
    }
  }
}
