// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type JarLayout = import("./jar-layout").JarLayout;

declare global {
  interface XpLayoutMap {
    "no.item.example:jar-layout": JarLayout;
  }
}
