// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type MenuItem = import("./menu-item").MenuItem;
export type Seo = import("./seo").Seo;

export type MixinMap = {
  "no-item-example"?: {
    "menu-item"?: MenuItem;
    seo?: Seo;
  };
};

declare global {
  interface XpMixin {
    "no-item-example"?: {
      "menu-item"?: MenuItem;
      seo?: Seo;
    };
  }
}
