// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type MixinUsage = {
  /**
   * Title
   */
  title?: string;

  /**
   * Street
   */
  street?: string;

  /**
   * Postal code
   */
  postalCode?: string;

  /**
   * Url
   */
  url: string;

  /**
   * Open in new tab
   */
  openInNewTab: boolean;

  /**
   * Links
   */
  links?: Array<import("../../mixins/link").Link>;

  /**
   * Titled link
   */
  titledLink?: {
    /**
     * Link title
     */
    linkTitle?: string;

    /**
     * Url
     */
    url: string;

    /**
     * Open in new tab
     */
    openInNewTab: boolean;
  };

  /**
   * Missing mixin only
   */
  missingMixinOnly?: {

  };

  /**
   * Link type
   */
  linkType?:
    | {
        /**
         * Selected
         */
        _selected: "internal";

        /**
         * Internal
         */
        internal: import("../../mixins/link").Link;
      }
    | {
        /**
         * Selected
         */
        _selected: "list";

        /**
         * List
         */
        list: import("../../mixins/link-list").LinkList;
      };

  /**
   * Link types
   */
  linkTypes?: {
    /**
     * Selected
     */
    _selected: Array<"internal">;
    
    /**
     * Internal
     */
    internal: import("../../mixins/link").Link;
  };
};
