// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type JarPage = import("./jar-page").JarPage;

export type PageMap = {
  "no.item.example:jar-page": JarPage;
};
