// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type _2Columns = import("./2-columns")._2Columns;
export type AllInputs = import("./all-inputs").AllInputs;
export type MixinUsage = import("./mixin-usage").MixinUsage;
export type NoForm = import("./no-form").NoForm;
export type Sets = import("./sets").Sets;

declare global {
  namespace XP {
    interface ContentTypes {
      "no.item.example:2-columns": _2Columns;
      "no.item.example:all-inputs": AllInputs;
      "no.item.example:mixin-usage": MixinUsage;
      "no.item.example:no-form": NoForm;
      "no.item.example:sets": Sets;
    }
  }
}
