// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Article = {
	/**
	 * Title
	 */
	title: string;

	/**
	 * Author
	 */
	author?: {
		/**
		 * Name
		 */
		name?: string;
	};

	/**
	 * Layout
	 */
	layout?:
		| {
				/**
				 * Selected
				 */
				_selected: "wide";

				/**
				 * Wide
				 */
				wide: Record<string, unknown>;
			}
		| {
				/**
				 * Selected
				 */
				_selected: "columns";

				/**
				 * Columns
				 */
				columns: {
					/**
					 * Count
					 */
					count?: number;
				};
			};
};
