// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type JarPart = import("./jar-part").JarPart;
export type LocalPart = import("./local-part").LocalPart;

declare global {
  interface XpPartMap {
    "no.item.example:jar-part": JarPart;
    "no.item.example:local-part": LocalPart;
  }
}
