// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Article = {
  /**
   * Title
   */
  title?: string;

  /**
   * Links
   */
  links?: Array<import("../../form-fragments/jar-link").JarLink>;
};
