// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type FragmentUsage = {
  /**
   * Title
   */
  title?: string;

  /**
   * Street
   */
  street?: string;

  /**
   * Postal code
   */
  postalCode?: string;

  /**
   * Url
   */
  url: string;

  /**
   * Open in new tab
   */
  openInNewTab: boolean;

  /**
   * Links
   */
  links?: Array<import("../../form-fragments/link").Link>;

  /**
   * Titled link
   */
  titledLink?: {
    /**
     * Link title
     */
    linkTitle?: string;

    /**
     * Url
     */
    url: string;

    /**
     * Open in new tab
     */
    openInNewTab: boolean;
  };

  /**
   * Missing form fragment only
   */
  missingFragmentOnly?: Record<string, never>;

  /**
   * Link type
   */
  linkType?:
    | {
        /**
         * Selected
         */
        _selected: "internal";

        /**
         * Internal
         */
        internal: import("../../form-fragments/link").Link;
      }
    | {
        /**
         * Selected
         */
        _selected: "list";

        /**
         * List
         */
        list: import("../../form-fragments/link-list").LinkList;
      };

  /**
   * Link types
   */
  linkTypes?: {
    /**
     * Selected
     */
    _selected: Array<"internal">;

    /**
     * Internal
     */
    internal: import("../../form-fragments/link").Link;
  };
};
