// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type _2Columns = import("./2-columns")._2Columns;
export type AllInputs = import("./all-inputs").AllInputs;
export type FragmentUsage = import("./fragment-usage").FragmentUsage;
export type NoForm = import("./no-form").NoForm;
export type Sets = import("./sets").Sets;
