// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Article = import("./article").Article;
export type JarArticle = import("./jar-article").JarArticle;

declare global {
  namespace XP {
    interface ContentTypes {
      "no.item.example:article": Article;
      "no.item.example:jar-article": JarArticle;
    }
  }
}
