// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type JarPage = import("./jar-page").JarPage;

declare global {
  interface XpPageMap {
    "no.item.example:jar-page": JarPage;
  }
}
